apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: adi
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: suricata-eve
        enabled: true
        paths:
          - /var/log/suricata/eve.json
        parsers:
          - ndjson:
              target: "suricata"
              add_error_key: true
        fields:
          source: suricata
          environment: radiant-lab
        fields_under_root: true

    output.elasticsearch:
      hosts: ["http://elasticsearch.monitoring.svc.cluster.local:9200"]
      index: "radiant-suricata-v3-%{+yyyy.MM.dd}"

    setup.template:
      name: "radiant-suricata-v3"
      pattern: "radiant-suricata-v3-*"
      enabled: true

    setup.kibana:
      host: "http://kibana.monitoring.svc.cluster.local:5601"

    logging.level: debug
    logging.selectors: ["*"]
    
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: adi
  labels:
    app: filebeat
    project: radiant
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
        project: radiant
    spec:
      serviceAccountName: filebeat-sa
      terminationGracePeriodSeconds: 30
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.13.4
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/filebeat.yml
            - -e
          securityContext:
            runAsUser: 0
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
            - name: suricata-logs
              mountPath: /var/log/suricata
              readOnly: true
      volumes:
        - name: filebeat-config
          configMap:
            name: filebeat-config
            defaultMode: 0640
        - name: suricata-logs
          hostPath:
            path: /var/log/suricata
            type: DirectoryOrCreate

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-sa
  namespace: adi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-role
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-binding
subjects:
  - kind: ServiceAccount
    name: filebeat-sa
    namespace: adi
roleRef:
  kind: ClusterRole
  name: filebeat-role
  apiGroup: rbac.authorization.k8s.io